// Generated by kea-typegen on Sat, 25 Feb 2023 16:17:50 GMT. DO NOT EDIT THIS FILE MANUALLY.
// @ts-nocheck

import type { Logic } from 'kea'

import type { Element } from '..\..\node_modules\@types\react\index.d'
import type { HomeProps } from '..\scenes\Home\HomeScene'
import type { EditExpenseProps } from '..\scenes\EditExpense\EditExpenseScene'
import type { ExpensesListProps } from '..\scenes\ExpensesList\ExpensesListScene'

export interface scenesLogicType extends Logic {
  actionCreators: {
    setScene: (
      scene: any,
      params: any
    ) => {
      type: 'set scene (app.logic)'
      payload: {
        scene: any
        params: any
      }
    }
  }
  actionKeys: {
    'set scene (app.logic)': 'setScene'
  }
  actionTypes: {
    setScene: 'set scene (app.logic)'
  }
  actions: {
    setScene: (scene: any, params: any) => void
  }
  asyncActions: {
    setScene: (scene: any, params: any) => Promise<any>
  }
  defaults: {
    scene: null
    params: {}
  }
  events: {}
  key: undefined
  listeners: {}
  path: ['app', 'logic']
  pathString: 'app.logic'
  props: Record<string, unknown>
  reducer: (
    state: any,
    action: any,
    fullState: any
  ) => {
    scene: null
    params: {}
  }
  reducers: {
    scene: (state: null, action: any, fullState: any) => null
    params: (state: {}, action: any, fullState: any) => {}
  }
  selector: (state: any) => {
    scene: null
    params: {}
  }
  selectors: {
    scene: (state: any, props?: any) => null
    params: (state: any, props?: any) => {}
    Component: (
      state: any,
      props?: any
    ) =>
      | (() => Element)
      | (({ children, date }: HomeProps) => Element)
      | (() => Element)
      | (({ id: expenseId }: EditExpenseProps) => Element)
      | (({ year, month }: ExpensesListProps) => Element)
  }
  sharedListeners: {}
  values: {
    scene: null
    params: {}
    Component:
      | (() => Element)
      | (({ children, date }: HomeProps) => Element)
      | (() => Element)
      | (({ id: expenseId }: EditExpenseProps) => Element)
      | (({ year, month }: ExpensesListProps) => Element)
  }
  _isKea: true
  _isKeaWithKey: false
  __keaTypeGenInternalSelectorTypes: {
    Component: (
      scene: null
    ) =>
      | (() => Element)
      | (({ children, date }: HomeProps) => Element)
      | (() => Element)
      | (({ id: expenseId }: EditExpenseProps) => Element)
      | (({ year, month }: ExpensesListProps) => Element)
  }
}
