// Generated by kea-typegen on Thu, 23 Feb 2023 16:04:37 GMT. DO NOT EDIT THIS FILE MANUALLY.
// @ts-nocheck

import type { Logic } from 'kea'

export interface homeLogicType extends Logic {
  actionCreators: {
    createNewExpense: () => {
      type: 'create new expense (scenes\\Home\\homeLogic)'
      payload: {
        value: true
      }
    }
  }
  actionKeys: {
    'create new expense (scenes\\Home\\homeLogic)': 'createNewExpense'
  }
  actionTypes: {
    createNewExpense: 'create new expense (scenes\\Home\\homeLogic)'
  }
  actions: {
    createNewExpense: () => void
  }
  asyncActions: {
    createNewExpense: () => Promise<any>
  }
  defaults: {}
  events: {}
  key: undefined
  listeners: {
    createNewExpense: ((
      action: {
        type: 'create new expense (scenes\\Home\\homeLogic)'
        payload: {
          value: true
        }
      },
      previousState: any
    ) => void | Promise<void>)[]
  }
  path: ['scenes\\Home\\homeLogic']
  pathString: 'scenes\\Home\\homeLogic'
  props: Record<string, unknown>
  reducer: (state: any, action: any, fullState: any) => {}
  reducers: {}
  selector: (state: any) => {}
  selectors: {}
  sharedListeners: {}
  values: {}
  _isKea: true
  _isKeaWithKey: false
}
